# Site name
site_name: Module 3 - Data Processing, Transformation & ETL
dev_addr: '0.0.0.0:8000'

# Navigation menu
nav:
  - Overview: index.md

  - Agenda:
    - Day 2: agenda/day2.md
    - Day 3: agenda/day3.md

  - "Day 2 - Microsoft Fabric":
    - "Lab 2.1 ~ 01 Create Fabric Lakehouse": labs/01-lakehouse.md
    - "Lab 2.2 ~ 05 Dataflows Gen2": labs/05-dataflows-gen2.md
    - "Lab 2.3 ~ 04 Ingest Pipeline": labs/04-ingest-pipeline.md

  - "Day 3 - Microsoft Fabric":
    - "Lab 3.1 - Create Medallion Architecture": day3/03b-medallion-architecture.md

  - Resources: resources.md

not_in_nav: |
  404.md
  trainer.md
  day1/transform-setup.md
  day1/transform-lab.md
  day1/extract-setup.md
  day1/extract-lab.md
   day2/etl-product.md
  day2/etl-product-report-back.md


# Theme
theme:
    features:
      - toc.integrate
      - content.code.copy
    name: material
    icon:
      logo: material/database

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: false
      toc_depth: 2

  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: false
  - pymdownx.tilde

plugins:
  - search


