uthisha add --day DE5M3D1 --time 09:20 --code OPEN --content "Day 1: Complete ELT Pipeline" --type "open" --link "http://192.168.1.227:3000/s/de5m3.md"
uthisha add --day DE5M3D1 --time 09:30 --code WELCOME --content "🌅 Welcome to Day 1 of DE5 Module 3" --type "" --link ""
uthisha add --day DE5M3D1 --time 09:40 --code VMSETUP --content "VM Setup" --type "" --link ""
uthisha add --day DE5M3D1 --time 09:50 --code VMSETUP --content "VM Setup" --type "" --link ""
uthisha add --day DE5M3D1 --time 10:00 --code TRANSFORM --content "ETL: Focus on Transform ~ Setup" --type "" --link "day1/transform-setup.md"
uthisha add --day DE5M3D1 --time 10:10 --code TRANSFORM-LAB --content "ETL Lab: Focus on Transform" --type "practice" --link "day1/transform-notebook.md"
uthisha add --day DE5M3D1 --time 10:20 --code TRANSFORM-LAB --content "ETL Lab: Focus on Transform" --type "practice" --link "day1/transform-notebook.md"
uthisha add --day DE5M3D1 --time 10:30 --code TRANSFORM-LAB --content "ETL Lab: Focus on Transform" --type "practice" --link "day1/transform-notebook.md"
uthisha add --day DE5M3D1 --time 10:40 --code TRANSFORM-LAB --content "ETL Lab: Focus on Transform" --type "practice" --link "day1/transform-notebook.md"
uthisha add --day DE5M3D1 --time 10:50 --code AMBREAK --content "☕ Morning Break" --type "break" --link ""
uthisha add --day DE5M3D1 --time 11:00 --code AMBREAK --content "☕ Morning Break" --type "break" --link ""
uthisha add --day DE5M3D1 --time 11:10 --code AUTOMATION --content "Automation in the workplace" --type "discussion" --link ""
uthisha add --day DE5M3D1 --time 11:20 --code EXTRACT-SETUP --content "ETL: Focus on Extract ~ Setup" --type "" --link "day1/extract-setup.md"
uthisha add --day DE5M3D1 --time 11:30 --code EXTRACT-LAB --content "ETL Lab: Focus on Extract" --type "practice" --link "day1/extract-notebook.md"
uthisha add --day DE5M3D1 --time 11:40 --code EXTRACT-LAB --content "ETL Lab: Focus on Extract" --type "practice" --link "day1/extract-notebook.md"
uthisha add --day DE5M3D1 --time 11:50 --code EXTRACT-LAB --content "ETL Lab: Focus on Extract" --type "practice" --link "day1/extract-notebook.md"
uthisha add --day DE5M3D1 --time 12:00 --code EXTRACT-LAB --content "ETL Lab: Focus on Extract" --type "practice" --link "day1/extract-notebook.md"
uthisha add --day DE5M3D1 --time 12:10 --code EXTRACT-LAB --content "ETL Lab: Focus on Extract" --type "practice" --link "day1/extract-notebook.md"
uthisha add --day DE5M3D1 --time 12:20 --code LUNCH --content "🥪🥤 Lunch Break" --type "break" --link ""
uthisha add --day DE5M3D1 --time 12:30 --code LUNCH --content "🥪🥤 Lunch Break" --type "break" --link ""
uthisha add --day DE5M3D1 --time 12:40 --code LUNCH --content "🥪🥤 Lunch Break" --type "break" --link ""
uthisha add --day DE5M3D1 --time 12:50 --code LUNCH --content "🥪🥤 Lunch Break" --type "break" --link ""
uthisha add --day DE5M3D1 --time 13:00 --code LUNCH --content "🥪🥤 Lunch Break" --type "break" --link ""
uthisha add --day DE5M3D1 --time 13:10 --code LUNCH --content "🥪🥤 Lunch Break" --type "break" --link ""
uthisha add --day DE5M3D1 --time 13:20 --code INTRODUCE --content "Introductions" --type "discussion" --link ""
uthisha add --day DE5M3D1 --time 13:30 --code INTRODUCE --content "Introductions" --type "discussion" --link ""
uthisha add --day DE5M3D1 --time 13:40 --code LOAD-SETUP --content "ETL: Focus on Load ~ Setup" --type "" --link "day1/load-setup.md"
uthisha add --day DE5M3D1 --time 13:50 --code LOAD-LAB --content "ETL Lab: Focus on Load" --type "practice" --link "day1/load-notebook.md"
uthisha add --day DE5M3D1 --time 14:00 --code LOAD-LAB --content "ETL Lab: Focus on Load" --type "practice" --link "day1/load-notebook.md"
uthisha add --day DE5M3D1 --time 14:10 --code LOAD-LAB --content "ETL Lab: Focus on Load" --type "practice" --link "day1/load-notebook.md"
uthisha add --day DE5M3D1 --time 14:20 --code LOAD-LAB --content "ETL Lab: Focus on Load" --type "practice" --link "day1/load-notebook.md"
uthisha add --day DE5M3D1 --time 14:30 --code PMBREAK --content "☕ Afternoon Break" --type "break" --link ""
uthisha add --day DE5M3D1 --time 14:40 --code PMBREAK --content "☕ Afternoon Break" --type "break" --link ""
uthisha add --day DE5M3D1 --time 14:50 --code PIPELINE-LAB --content "ETL Lab: Full ETL Pipeline" --type "practice" --link "day1/load-notebook.md"
uthisha add --day DE5M3D1 --time 15:00 --code PIPELINE-LAB --content "ETL Lab: Full ETL Pipeline" --type "practice" --link "day1/load-notebook.md"
uthisha add --day DE5M3D1 --time 15:10 --code PIPELINE-LAB --content "ETL Lab: Full ETL Pipeline" --type "practice" --link "day1/load-notebook.md"
uthisha add --day DE5M3D1 --time 15:20 --code PIPELINE-LAB --content "ETL Lab: Full ETL Pipeline" --type "practice" --link "day1/load-notebook.md"
uthisha add --day DE5M3D1 --time 15:30 --code PIPELINE-LAB --content "ETL Lab: Full ETL Pipeline" --type "practice" --link "day1/load-notebook.md"
uthisha add --day DE5M3D1 --time 15:40 --code REFLECT --content "End of day reflections" --type "discussion" --link ""
uthisha add --day DE5M3D1 --time 15:50 --code WRAP --content "🎁 Wrap" --type "wrap" --link ""
uthisha add --day DE5M3D1 --time 16:00 --code CLOSE --content "❌" --type "close" --link ""
