[project]
site_name = "Module 3 - Data Processing, Transformation & ETL"
dev_addr = "0.0.0.0:8000"

nav = [
  {"Overview" = "index.md"},
  {"Agenda" = [
    {"Day 2" = "agenda/day2.md"},
    {"Day 3" = "agenda/day3.md"},
  ]},
  {"Resources" = "resources.md"},
]

