[project]
site_name = "Module 3 - Data Processing, Transformation & ETL"
dev_addr = "0.0.0.0:8000"

nav = [
  {"Overview" = "index.md"},
  {"Agenda" = [
    {"Day 2" = "agenda/day2.md"},
    {"Day 3" = "agenda/day3.md"},
  ]},
  {"Day 2 - Microsoft Fabric" = [
    {"Lab ~ 01 Create Fabric Lakehouse" = "labs/01-lakehouse.md"},
    {"Architecture Investigation" = "day2/architecture-investigation.md"},
    {"Lab ~ 05 Dataflows Gen2" = "labs/05-dataflows-gen2.md"},
    {"Lab ~ 04 Ingest Pipeline" = "labs/04-ingest-pipeline.md"},
  ]},
  {"Day 3 - Microsoft Fabric" = [
    {"Medallion Architecture Investigation" = "day3/medallion/group-scenarios.md"},
    {"Lab 3.1 - Create Medallion Architecture" = "day3/03b-medallion-architecture.md"},
  ]},
  {"Resources" = "resources.md"},
]


[project.theme]
variant = "classic"

features = [
  "announce.dismiss",
  "content.code.annotate",
  "content.code.copy",
  "content.code.select",
  #"content.action.edit",
  #"content.action.view",
  "navigation.sections",
  #"navigation.expand",
  #"navigation.footer",
  #"navigation.instant",
  #"navigation.instant.prefetch",
  #"navigation.instant.progress",
  #"navigation.path",
  "navigation.sections",
  #"navigation.tabs",
  #"navigation.tabs.sticky",
  "navigation.top",
  #"navigation.tracking",
  #"search.highlight",
  # "toc.follow",
  "toc.integrate",
]
    
[[project.theme.palette]]
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"
    
[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"
    
[project.theme.icon]
logo = material/database
    
