[project]
site_name = "Module 3 - Data Processing, Transformation & ETL"
dev_addr = "0.0.0.0:8000"

nav = [
  {"Overview" = "index.md"},
  {"Agenda" = [
    {"Day 1" = "agenda/day1.md"},
    {"Day 2" = "agenda/day2.md"},
    {"Day 3" = "agenda/day3.md"},
    {"Day 4" = "agenda/day4.md"},
  ]},
  {"Day 1 - ETL Locally" = [
    {"🖥️ VM Setup" = "https://qaalabs.github.io/vmsetup/"},
    {"Git Clone the Data Files" = "labs/11-setup.md"},
    {"Introducing HomeSphere" = "day1/homesphere.md"},
    {"Part 1 ~ Inspect Sales Data" = "day1/inspect-sales.md"},
    {"Part 2 ~ Inspect Product Data" = "day1/inspect-prod.md"},
    {"Part 3 ~ Clean Sales Data" = "day1/clean-sales.md"},
    {"Flatten and Join" = "day1/flatten-join.md"},
    {"ETL Pipeline ~ Stretch Task" = "day1/stretch-etl-script.md"},
    {"ETL Product Investigation" = "day1/etl-products.md"},
  ]},
  {"Day 2 - ETL in the Cloud" = [
    {"Lab 2.1 - Explore Fabric Environment" = "labs/21-lakehouse.md"},
    {"Lab 2.2 - Landing Raw Data" = "labs/22-land-data.md"},
    {"Lab 2.3 - Clean the Sales Data" = "labs/23-cloud-clean.md"},
    {"Choosing a Data Architecture" = "day2/architecture-investigation.md"},
    {"Lab 2.4 - Setup Fabric" = "labs/24-pm-setup.md"},
    {"Lab 2.5 - Build the Trusted Output" = "labs/25-cloud-output.md"},
    {"Lab 2.6 - Create ETL Pipeline" = "labs/26-etl-pipeline.md"},
    {"Lab 2.7 ~ Rerun Pipeline" = "labs/27-rerun-pipeline.md"},
    {"Lab 2.8 ~ Schema Drift" = "labs/28-schema-drift.md"},
    {"Lab 2.9 ~ Pipeline Failure" = "labs/29-pipeline-failure.md"},
  ]},
  {"Day 3 - Robust & Well-Architectured" = [
    {"Swagger ~ Read from a Live API" = "day3/swagger-lab.md"},
    {"Where are the Weaknesses?" = "day3/fragile.md"},
    {"Map the Pipeline" = "day3/medallion-mapping.md"},
    {"Lab 3.1 - Setup Fabric" = "labs/31-setup.md"},
    {"Lab 3.2 - Medallion Architecture" = "labs/32-medallion-lab.md"},
    {"Medallion Scenarios" = "day3/medallion-scenarios.md"},
  ]},
  {"Day 4 - Supportable & Explainable" = [
    {"Silent Failures" = "day4/silent-fail.md"},
    {"Add Validation Checks" = "day4/checks-build.md"},
    {"Run the Pipeline Locally" = "day4/pipeline-local.md"},
    {"Create a Handover Artefact" = "day4/mvd-build.md"},
    {"Deploy a New Pipeline" = "day4/deploy-guide.md"},
    {"Prepare Your Explanation" = "day4/pitch-prep.md"},
    {"Evaluate New Change Request" = "day4/change-respond.md"},
  ]},
  {"Resources" = "resources.md"},
]


[project.theme]
variant = "classic"

features = [
  "announce.dismiss",
  "content.code.annotate",
  "content.code.copy",
  "content.code.select",
  "toc.integrate",

  #"content.action.edit",
  #"content.action.view",
  #"header.autohide",
  #"navigation.expand",
  #"navigation.footer",
  #"navigation.instant",
  #"navigation.instant.prefetch",
  #"navigation.instant.progress",
  #"navigation.path",
  #"navigation.sections",
  #"navigation.tabs",
  #"navigation.tabs.sticky",
  #"navigation.top",
  #"navigation.tracking",
  #"search.highlight",
  #"toc.follow",
]
    
[[project.theme.palette]]
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"
    
[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"
    
[project.theme.icon]
logo = "material/database"
    
